<?php

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Url;
use Drupal\taxonomy\Entity\Term;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_preprocess_breadcrumb().
 */
function my_module_preprocess_breadcrumb(array &$variables)
{
  $variables['breadcrumb'][0]['text'] = "HOME";
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name === 'view.home.page_1') {
    $variables['breadcrumb'] = [];
  }

  if ($route_name === 'view.categories.page_1') {
    $slug = \Drupal::routeMatch()->getRawParameter('arg_0');
    $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties([
      'field_url.uri' => 'internal:/product/' . $slug,
    ]);

    $term = reset($terms);
    if ($term) {
      $term_label = $term->label();
      $uri = $term->field_url->uri;
      $term_url = Url::fromUri($uri)->toString();
      foreach ($variables['breadcrumb'] as $key => $breadcrumb) {
        if ($breadcrumb['text'] === 'Categories') {
          $variables['breadcrumb'][$key]['text'] = $term_label;
          $variables['breadcrumb'][$key]['url'] = $term_url;
        }
      }
    }
  }

  if ($route_name === 'entity.taxonomy_term.canonical') {
    $term = \Drupal::routeMatch()->getParameter('taxonomy_term');
    $parent_term = $term->get('parent')->entity;
    if ($parent_term) {
      $parent_label = $parent_term->label();
      foreach ($variables['breadcrumb'] as $key => $breadcrumb) {
        if ($breadcrumb['text'] === 'Categories') {
          $variables['breadcrumb'][$key]['text'] = $parent_label;
        }
        if ($breadcrumb['text'] === $term->label()) {
          $uri = $term->field_url->uri;
          $term_url = Url::fromUri($uri)->toString();
          $variables['breadcrumb'][$key]['url'] = $term_url;
        }
      }
    }
  }

  if ($route_name === 'view.product_detail.page_1') {
    $route_match = \Drupal::routeMatch();
    $view = $route_match->getParameter('view_id');
    $view = \Drupal\views\Views::getView($view);
    if ($view instanceof ViewExecutable) {
      $view->setDisplay('page_1');
      $view->preExecute(); // hoặc execute() nếu bạn cần chạy toàn bộ
      $view->execute();

      $results = $view->result;
      if (sizeof($variables['breadcrumb']) == 4) {
        $entity = $results[0]->_entity;
        $field_category = $entity->get('field_category')->referencedEntities();
        $category_entity =  $field_category[0];
        $parent_ids = $category_entity->get('parent')->getValue();
        $parent_tid = $parent_ids[0]['target_id'];
        $parent_term = Term::load($parent_tid);
        $variables['breadcrumb'][2]['text'] = $parent_term->label();
        $variables['breadcrumb'][4]['text'] =  $entity->get('field_product_name')->value;
        $variables['breadcrumb'][4]['url'] =  $entity->field_url->uri;
      }
    }
  }

  if ($route_name === 'view.product_spec.page_1') {
    $route_match = \Drupal::routeMatch();
    $view = $route_match->getParameter('view_id');
    $view = \Drupal\views\Views::getView($view);
    if ($view instanceof ViewExecutable) {
      $view->setDisplay('page_1');
      $view->preExecute();
      $view->execute();

      $results = $view->result;
      if (sizeof($results) > 0) {
        $entity = $results[0]->_entity;
        $product_entity = $entity->get('field_product')->entity;
        $field_category = $product_entity->get('field_category')->referencedEntities();
        $category_entity =  $field_category[0];
        $parent_ids = $category_entity->get('parent')->getValue();
        $parent_tid = $parent_ids[0]['target_id'];
        $parent_term = Term::load($parent_tid);
        $variables['breadcrumb'][2]['text'] = $parent_term->label();
        $variables['breadcrumb'][4]['text'] =  $product_entity->get('field_product_name')->value;
        $variables['breadcrumb'][5]['text'] =  $product_entity->get('field_product_name')->value . '　仕様';
        $variables['breadcrumb'][5]['url'] =  $entity->get('field_url_spec')->value;
      }
    }
  }
}

function my_module_views_query_alter(ViewExecutable $view, QueryPluginBase $query)
{
  if ($view->id() == 'categories' && $view->current_display == 'page_1') {
    $arg = \Drupal::routeMatch()->getRawParameter('arg_0');
    $query->addWhere(0, 'taxonomy_term__field_url.field_url_uri', "internal:/product/$arg", '=');
  }

  if ($view->id() === 'product_detail') {
    $arg = \Drupal::routeMatch()->getRawParameter('arg_2');
    $query->addWhere(0, 'node__field_slug.field_slug_value', "$arg", '=');
  }

  if ($view->id() === 'product_spec') {
    $params = \Drupal::routeMatch()->getRawParameters()->all();
    $arg_values = array_filter($params, function ($key) {
      return str_starts_with($key, 'arg_');
    }, ARRAY_FILTER_USE_KEY);

    $arg = implode('/', $arg_values);
    $query->addWhere(0, 'node__field_url_spec.field_url_spec_value', "/product/$arg", '=');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function my_module_form_node_product_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  if (isset($form['field_url'])) {
    $form['field_url']['#type'] = 'hidden';
    $form['field_url']['#access'] = FALSE;
  }
}

/**
 * Implements hook_entity_presave().
 */
function my_module_entity_presave(\Drupal\Core\Entity\EntityInterface $entity)
{
  if ($entity instanceof NodeInterface && $entity->bundle() === 'product') {
    // Save status 
    $entity->original_moderation_state = $entity->original ? $entity->original->get('moderation_state')->value : NULL;
    $term = $entity->get('field_category')->entity;
    $url = $term->field_url->uri;
    $category_url = $term->url_redirect = Url::fromUri($url)->toString();
    $slug = $entity->get('field_slug')->value;
    $final_url = '/' . trim($category_url, '/') . '/' . $slug;

    $entity->set('field_url', $final_url);
  }

  if ($entity instanceof NodeInterface && $entity->bundle() === 'product_spec') {
    // Save status 
    $product = $entity->get('field_product')->entity;
    $url = $product->field_url->uri;
    $final_url = '/' . trim($url, '/') . '/spec';
    $entity->set('field_url_spec', $final_url);
  }
}

/**
 * Implements hook_entity_insert().
 */
function my_module_entity_insert(\Drupal\Core\Entity\EntityInterface $entity)
{
  if ($entity instanceof NodeInterface && $entity->bundle() === 'product') {
    $old_state = $entity->original_moderation_state ?? NULL;
    $new_state = $entity->get('moderation_state')->value;
    if ($old_state === 'draft' && $new_state === 'needs_review') {
      $users = \Drupal::entityTypeManager()->getStorage('user')->loadByProperties(['status' => 1]);
      foreach ($users as $user) {
        if (in_array('content_approver', $user->getRoles())) {
          $to = $user->getEmail();
          $mailManager = \Drupal::service('plugin.manager.mail');
          $params['product_title'] = $entity->get('field_product_name')->value;
          $edit_url = Url::fromRoute('entity.node.edit_form', ['node' => $entity->id()], [
            'query' => ['destination' => '/admin/content'],
            'absolute' => TRUE,
          ])->toString();
          $params['url_edit'] = $edit_url;
          $mailManager->mail('my_module', 'notify_create', $to, \Drupal::languageManager()->getDefaultLanguage()->getId(), $params);
        }
      }
    }
  }
}

/**
 * Send Mail Update.
 */
function my_module_entity_update(\Drupal\Core\Entity\EntityInterface $entity)
{
  if ($entity instanceof NodeInterface && $entity->bundle() === 'product') {
    $old_state = $entity->original_moderation_state ?? NULL;
    $new_state = $entity->get('moderation_state')->value;
    if ($old_state === 'draft' && $new_state === 'needs_review') {
      $users = \Drupal::entityTypeManager()->getStorage('user')->loadByProperties(['status' => 1]);
      foreach ($users as $user) {
        if (in_array('content_approver', $user->getRoles())) {
          $to = $user->getEmail();
          $mailManager = \Drupal::service('plugin.manager.mail');
          $params['product_title'] = $entity->get('field_product_name')->value;
          $edit_url = Url::fromRoute('entity.node.edit_form', ['node' => $entity->id()], [
            'query' => ['destination' => '/admin/content'],
            'absolute' => TRUE,
          ])->toString();
          $params['url_edit'] = $edit_url;
          $mailManager->mail('my_module', 'notify_update', $to, \Drupal::languageManager()->getDefaultLanguage()->getId(), $params);
        }
      }
    }
  }
}


function my_module_mail($key, &$message, $params)
{
  switch ($key) {
    case 'notify_create':
      $message['subject'] = 'A new product has been added';
      $message['body'][] = "Hello,

A new product has just been added to the system.

📦 Product name:「" . $params['product_title'] . "」

Please visit the admin page to review and approve:
👉 " . $params['url_edit'] . "

Best regards,
IoData System";
      break;

    case 'notify_update':
      $message['subject'] = 'A new product has been added';
      $message['body'][] = "Hello,
  
  A product has just been updated to the system.
  
  📦 Product name:「" . $params['product_title'] . "」
  
  Please visit the admin page to review and approve:
  👉 " . $params['url_edit'] . "
  
  Best regards,
  IoData System";
      break;
  }
}

/**
 * Implements hook_node_access().
 */
function my_module_node_access(NodeInterface $node, $op, AccountInterface $account)
{
  if ($node->bundle() === 'product') {
    if (in_array('content_creator', $account->getRoles())) {
      if ($node->hasField('moderation_state')) {
        $state = $node->get('moderation_state')->value;
        if ($state !== 'draft') {
          return \Drupal\Core\Access\AccessResult::forbidden();
        }
      }
    }
  }
  return \Drupal\Core\Access\AccessResult::neutral();
}


/**
 * Implements hook_menu_local_tasks_alter().
 */
function my_module_menu_local_tasks_alter(&$data, $route_name)
{
  $route_match = \Drupal::routeMatch();
  $node = $route_match->getParameter('node');
  $account = \Drupal::currentUser();

  if ($node instanceof NodeInterface && $node->bundle() === 'product') {
    if (in_array('content_creator', $account->getRoles())) {
      if ($node->hasField('moderation_state') && $node->get('moderation_state')->value !== 'draft') {
        if (isset($data['tabs'][0]['#links']['node.delete'])) {
          unset($data['tabs'][0]['#links']['node.delete']);
        }
      }
    }
  }
}


/**
 * Implements hook_breadcrumb_alter().
 */
function my_module_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match)
{
  if ($term = $route_match->getParameter('taxonomy_term')) {
    if ($term instanceof Term) {
      $breadcrumb = new Breadcrumb();
      $breadcrumb->addLink(Link::createFromRoute('Home', '<front>'));

      $parents = \Drupal::entityTypeManager()
        ->getStorage('taxonomy_term')
        ->loadAllParents($term->id());

      $parents = array_reverse($parents);

      foreach ($parents as $parent_term) {
        if ($parent_term->id() == $term->id()) {
          continue;
        }

        $url = $parent_term->get('field_url')->uri ?? $parent_term->toUrl()->toString();

        if (strpos($url, 'internal:') === 0) {
          $url = substr($url, strlen('internal:'));
        }

        $breadcrumb->addLink(Link::fromTextAndUrl(
          $parent_term->label(),
          \Drupal\Core\Url::fromUserInput($url)
        ));
      }
    }
  }
}
