<?php

use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

function my_module_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'categories' && $view->current_display == 'page_1') {
    $arg = \Drupal::routeMatch()->getRawParameter('arg_0');
    $query->addWhere(0, 'taxonomy_term__field_url.field_url_uri', "internal:/product/$arg", '=');
  }

  if ($view->id() === 'product_detail') {
    $arg = \Drupal::routeMatch()->getRawParameter('arg_2');
    $query->addWhere(0, 'node__field_slug.field_slug_value', "$arg", '=');
    // dd($query);
  }
}